FROM node:22-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci

FROM node:22-alpine AS build
WORKDIR /app

ARG NODE_ENV
ARG APP_BASE_URL
ARG NEXT_PUBLIC_APP_URL
ARG TRUSTED_PROXY
ARG APP_DATABASE_URL
ARG REDIS_URL
ARG MYSQL_HOST
ARG MYSQL_PORT
ARG MYSQL_USER
ARG MYSQL_PASSWORD
ARG MYSQL_DATABASE
ARG MYSQL_CONNECTION_LIMIT
ARG MYSQL_CONNECT_TIMEOUT_MS
ARG MINIO_ENDPOINT
ARG MINIO_PUBLIC_URL
ARG MINIO_ACCESS_KEY
ARG MINIO_SECRET_KEY
ARG MINIO_BUCKET
ARG MINIO_REGION
ARG POS_API_EMAIL
ARG POS_API_PASSWORD
ARG POS_AUTH_URL
ARG POS_API_BASE_URL
ARG POS_IMPORT_URL
ARG POS_BRANCH_URL
ARG POS_MERCHANT_ID_BASE_URL
ARG POS_CATEGORY_BUSINESS_BASE_URL
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG GOOGLE_REDIRECT_URI
ARG GOOGLE_WORKSPACE_DOMAINS
ARG SMTP_HOST
ARG SMTP_PORT
ARG SMTP_SECURE
ARG SMTP_USER
ARG SMTP_PASS
ARG SMTP_FROM_EMAIL
ARG SMTP_FROM_NAME
ARG CLICKUP_SYNC_CRON_SECRET
ARG CLICKUP_API_TOKEN
ARG CLICKUP_LIST_ID
ARG CLICKUP_API_BASE_URL
ARG CLICKUP_CUSTOM_FIELD_PRODUCT_ID
ARG CLICKUP_CUSTOM_FIELD_DEPARTMENT_REQUEST_ID
ARG CLICKUP_CUSTOM_FIELD_PRIORITY_LEVEL_ID
ARG CLICKUP_CUSTOM_FIELD_SEVERITY_LEVEL_ID
ARG NEXT_PUBLIC_CLICKUP_ENABLED
ARG SUPPORTFORM_WHATSAPP_NUMBER
ARG DEMOFORM_WHATSAPP_NUMBER
ARG NEXT_PUBLIC_SUPPORT_PHONE
ARG NEXT_PUBLIC_SUPPORT_EMAIL
ARG NEXT_PUBLIC_SUPPORT_CONTACT
ARG NEXT_PUBLIC_SUPPORT_WHATSAPP
ARG NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN
ARG NEXT_PUBLIC_RECAPTCHA_SITE_KEY
ARG RECAPTCHA_SECRET_KEY
ARG HUBSPOT_ACCESS_TOKEN
ARG HUBSPOT_BUSINESS_TYPE_PROPERTY
ARG HUBSPOT_BUSINESS_LOCATION_PROPERTY
ARG HUBSPOT_SOURCE_PROPERTY

ENV NODE_ENV=${NODE_ENV:-production}
ENV APP_BASE_URL=$APP_BASE_URL
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV TRUSTED_PROXY=$TRUSTED_PROXY
ENV DATABASE_URL=$APP_DATABASE_URL
ENV REDIS_URL=$REDIS_URL
ENV MYSQL_HOST=$MYSQL_HOST
ENV MYSQL_PORT=$MYSQL_PORT
ENV MYSQL_USER=$MYSQL_USER
ENV MYSQL_PASSWORD=$MYSQL_PASSWORD
ENV MYSQL_DATABASE=$MYSQL_DATABASE
ENV MYSQL_CONNECTION_LIMIT=$MYSQL_CONNECTION_LIMIT
ENV MYSQL_CONNECT_TIMEOUT_MS=$MYSQL_CONNECT_TIMEOUT_MS
ENV MINIO_ENDPOINT=$MINIO_ENDPOINT
ENV MINIO_PUBLIC_URL=$MINIO_PUBLIC_URL
ENV MINIO_ACCESS_KEY=$MINIO_ACCESS_KEY
ENV MINIO_SECRET_KEY=$MINIO_SECRET_KEY
ENV MINIO_BUCKET=$MINIO_BUCKET
ENV MINIO_REGION=$MINIO_REGION
ENV POS_API_EMAIL=$POS_API_EMAIL
ENV POS_API_PASSWORD=$POS_API_PASSWORD
ENV POS_AUTH_URL=$POS_AUTH_URL
ENV POS_API_BASE_URL=$POS_API_BASE_URL
ENV POS_IMPORT_URL=$POS_IMPORT_URL
ENV POS_BRANCH_URL=$POS_BRANCH_URL
ENV POS_MERCHANT_ID_BASE_URL=$POS_MERCHANT_ID_BASE_URL
ENV POS_CATEGORY_BUSINESS_BASE_URL=$POS_CATEGORY_BUSINESS_BASE_URL
ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
ENV GOOGLE_REDIRECT_URI=$GOOGLE_REDIRECT_URI
ENV GOOGLE_WORKSPACE_DOMAINS=$GOOGLE_WORKSPACE_DOMAINS
ENV SMTP_HOST=$SMTP_HOST
ENV SMTP_PORT=$SMTP_PORT
ENV SMTP_SECURE=$SMTP_SECURE
ENV SMTP_USER=$SMTP_USER
ENV SMTP_PASS=$SMTP_PASS
ENV SMTP_FROM_EMAIL=$SMTP_FROM_EMAIL
ENV SMTP_FROM_NAME=$SMTP_FROM_NAME
ENV CLICKUP_SYNC_CRON_SECRET=$CLICKUP_SYNC_CRON_SECRET
ENV CLICKUP_API_TOKEN=$CLICKUP_API_TOKEN
ENV CLICKUP_LIST_ID=$CLICKUP_LIST_ID
ENV CLICKUP_API_BASE_URL=$CLICKUP_API_BASE_URL
ENV CLICKUP_CUSTOM_FIELD_PRODUCT_ID=$CLICKUP_CUSTOM_FIELD_PRODUCT_ID
ENV CLICKUP_CUSTOM_FIELD_DEPARTMENT_REQUEST_ID=$CLICKUP_CUSTOM_FIELD_DEPARTMENT_REQUEST_ID
ENV CLICKUP_CUSTOM_FIELD_PRIORITY_LEVEL_ID=$CLICKUP_CUSTOM_FIELD_PRIORITY_LEVEL_ID
ENV CLICKUP_CUSTOM_FIELD_SEVERITY_LEVEL_ID=$CLICKUP_CUSTOM_FIELD_SEVERITY_LEVEL_ID
ENV NEXT_PUBLIC_CLICKUP_ENABLED=$NEXT_PUBLIC_CLICKUP_ENABLED
ENV SUPPORTFORM_WHATSAPP_NUMBER=$SUPPORTFORM_WHATSAPP_NUMBER
ENV DEMOFORM_WHATSAPP_NUMBER=$DEMOFORM_WHATSAPP_NUMBER
ENV NEXT_PUBLIC_SUPPORT_PHONE=$NEXT_PUBLIC_SUPPORT_PHONE
ENV NEXT_PUBLIC_SUPPORT_EMAIL=$NEXT_PUBLIC_SUPPORT_EMAIL
ENV NEXT_PUBLIC_SUPPORT_CONTACT=$NEXT_PUBLIC_SUPPORT_CONTACT
ENV NEXT_PUBLIC_SUPPORT_WHATSAPP=$NEXT_PUBLIC_SUPPORT_WHATSAPP
ENV NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN=$NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN
ENV NEXT_PUBLIC_RECAPTCHA_SITE_KEY=$NEXT_PUBLIC_RECAPTCHA_SITE_KEY
ENV RECAPTCHA_SECRET_KEY=$RECAPTCHA_SECRET_KEY
ENV HUBSPOT_ACCESS_TOKEN=$HUBSPOT_ACCESS_TOKEN
ENV HUBSPOT_BUSINESS_TYPE_PROPERTY=$HUBSPOT_BUSINESS_TYPE_PROPERTY
ENV HUBSPOT_BUSINESS_LOCATION_PROPERTY=$HUBSPOT_BUSINESS_LOCATION_PROPERTY
ENV HUBSPOT_SOURCE_PROPERTY=$HUBSPOT_SOURCE_PROPERTY

COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

FROM node:22-alpine AS runner
WORKDIR /app
RUN apk add --no-cache curl
ENV NODE_ENV=production
ENV HOSTNAME=0.0.0.0
ENV PORT=3000
COPY --from=build /app/.next/standalone ./
COPY --from=build /app/public ./public
COPY --from=build /app/.next/static ./.next/static
EXPOSE 3000
HEALTHCHECK --interval=30s --timeout=5s --start-period=30s --retries=3 CMD curl -fsS http://localhost:3000/ >/dev/null || exit 1
CMD ["node", "server.js"]
